# Álgebra Linear com SymPy

Um vetor $\vec{v} \in \mathbb{R}$ é uma **n-tupla** de números reais. Por exemplo, considere um vetor com três componentes:

\begin{equation}\vec{v} = (v1, v2, v3) \in (\mathbb{R}, \mathbb{R}, \mathbb{R}) \equiv \mathbb{R}³\end{equation}

Uma matriz $A \in \mathbb{R}^{m \times n}$ é um array retangular de números reais com $m$ linhas e $n$ colunas. 

Um vetor é uma matriz especial. Nós podemos pensar o vetor como $\vec{v} \in \mathbb{R}^n$

- Ou um vetor de linhas: $(1 \times n ~ matriz)$

- Ou um vetor de colunas: $(n \times 1 ~ matriz)$

Por causa dessa equivalência, não há um objeto vetor especial em SymPy e objetos de Matriz são utilizados para vetores também.

## Exemplos

Para iniciamors com os nossos exemplos, primeiro é necessário importar a biblioteca [SymPy](https://docs.sympy.org/latest/index.html).

In [1]:
from sympy import *
init_printing()

#### Definimos um vetor de linhas (1x3)

In [2]:
u = Matrix(1,3,[4,5,6]) 

In [3]:
u

[4  5  6]

#### Definimos um vetor de colunas (3x1)

In [4]:
v = Matrix([7,8,9]) 

In [5]:
v

⎡7⎤
⎢ ⎥
⎢8⎥
⎢ ⎥
⎣9⎦

#### Fazemos a transposição do vetor **v**

In [6]:
v.T

[7  8  9]

#### Apresenta o primeiro componente do vetor **u** (índices começam por 0, assim como no Python tradicional)

In [7]:
u[0] 

#### Mostra o comprimento do vetor

In [8]:
u.norm() 

#### Computamos o vetor de comprimento de unidade, (mesma direção de **u**)

In [9]:
uhat = u / u.norm() 
print(uhat)
uhat.norm()

Matrix([[4*sqrt(77)/77, 5*sqrt(77)/77, 6*sqrt(77)/77]])


O produto escalar dos vetores $\vec{u}$ e $\vec{v}$ pode ser definido como:

\begin{equation}\vec{u} \cdot \vec{v} \equiv u_x v_x + u_y v_y + u_z v_z \equiv ||{\vec{u}}|| ~ ||{\vec{v}}|| \cos (\varphi) \in \mathbb{R}\end{equation}

onde $\varphi$ é o ângulo entre os vetores $\vec{u}$ e $\vec{v}$.

Por exemplo:

In [12]:
u = Matrix(1,3,[4,5,6])
v = Matrix([-1,1,2])
u.dot(v)

Para calcular o ângulo entre dois vetores, nós transformamos a equação anterior para:

\begin{equation} \cos(\varphi) = \frac{\vec{u} \cdot \vec{v}}{||\vec{u}|| ~ ||\vec{v}||}\end{equation}

In [13]:
acos(u.dot(v)/(u.norm()*v.norm())).evalf()

O produto escalar é uma operação comutativa:

\begin{equation} \vec{u} \cdot \vec{v} = \vec{v} \cdot \vec{u} \end{equation}

In [14]:
u.dot(v) == v.dot(u)

True

O produto escalar também é utilizado para calcular projeções. 

Assumindo que você tenha dois vetores $\vec{v}$ e $\vec{n}$ e você deseja encontrar o componente de $\vec{v}$ que aponta para a direção $\vec{n}$

\begin{equation} \prod_\vec{n}(\vec{v}) \equiv \frac{\vec{v} \cdot \vec{n}}{||\vec{n}||^2}\vec{n} \end{equation}

Em SymPy, isso se traduziria como:

In [16]:
v = Matrix([4,5,6])
n = Matrix([1,1,1])
projeção = (u.dot(n)/n.norm()**2) * n # 
projeção

⎡5⎤
⎢ ⎥
⎢5⎥
⎢ ⎥
⎣5⎦

Acima estamos calculando a **projeção** de **v** na direção **n**.

O produto vetorial, denotado por $\times$, recebe dois vetores como input e produz um vetor como output:

\begin{equation}\vec{u} \times \vec{v} = (u_yv_z - u_zv_y,u_zv_x - u_xv_z,u_xv_y - u_y,v_x)\end{equation}

Definindo símbolos individuais para as entradas dos dois vetores, nós podemos fazer SymPy nos mostrar a fórmula do produto vetorial:

In [17]:
u1, u2, u3 = symbols('u1:4')
v1, v2, v3 = symbols('v1:4')
Matrix([u1,u2,u3]).cross(Matrix([v1,v2,v3]))

⎡u₂⋅v₃ - u₃⋅v₂ ⎤
⎢              ⎥
⎢-u₁⋅v₃ + u₃⋅v₁⎥
⎢              ⎥
⎣u₁⋅v₂ - u₂⋅v₁ ⎦

O produto vetorial é anticomutativo $\vec{u} \times \vec{v} = -\vec{v} \times \vec{u}$

In [18]:
u = Matrix([4,5,6])
v = Matrix([-1,1,2])
u.cross(v), v.cross(u)

⎛⎡ 4 ⎤  ⎡-4⎤⎞
⎜⎢   ⎥  ⎢  ⎥⎟
⎜⎢-14⎥, ⎢14⎥⎟
⎜⎢   ⎥  ⎢  ⎥⎟
⎝⎣ 9 ⎦  ⎣-9⎦⎠

Vamos agora olhar algumas particularidades das Matrizes.

Começaremos definindo uma nova Matriz $A$:

In [20]:
A = Matrix([[2, -3, -8, 7], [-2, -2 , 2, -7], [1, 0, -3, 6]])
A

⎡2   -3  -8  7 ⎤
⎢              ⎥
⎢-2  -2  2   -7⎥
⎢              ⎥
⎣1   0   -3  6 ⎦

Como visto anteriormente, nós podemos usar a indexação de Python para acessarmos elementos e submatrizes.

A seguir, acessamos a linha **0**, coluna **1** da matriz $A$:

In [21]:
A[0,1] 

Também podemos selecionar uma submatriz de $A$.

Neste exemplo, vamos selecionar as duas primeiras linhas e 3 primeiras colunas:

In [22]:
A[0:2, 0:3]

⎡2   -3  -8⎤
⎢          ⎥
⎣-2  -2  2 ⎦

Algumas matrizes usadas com frequência podem ser definidas através dos seguintes atalhos.

**eye** nos permite criar uma matriz identidade:

In [23]:
eye(2)

⎡1  0⎤
⎢    ⎥
⎣0  1⎦

**zeros** nos permite criar uma matriz com zeros:

In [24]:
zeros(2, 3)

⎡0  0  0⎤
⎢       ⎥
⎣0  0  0⎦

**ones** nos permite criar uma matriz somente de um:

In [25]:
ones(1,5)

[1  1  1  1  1]

**diag** nos permite criar uma matriz diagonal:

In [26]:
diag(1,2,3)

⎡1  0  0⎤
⎢       ⎥
⎢0  2  0⎥
⎢       ⎥
⎣0  0  3⎦

Operações algébricas padrões como **adição**, **subtração**, **multiplicação** e **exponenciação** funcionam como esperados para objetos de Matriz.

O método **transpose()** gira a matriz através de sua diagonal:

In [27]:
A.transpose()

⎡2   -2  1 ⎤
⎢          ⎥
⎢-3  -2  0 ⎥
⎢          ⎥
⎢-8  2   -3⎥
⎢          ⎥
⎣7   -7  6 ⎦

O determinante de uma matriz é denotado como $det(M)$ ou $|M|$ e pode ser calculado em SymPy como:

In [28]:
M = Matrix([[1, 2, 3], [2, -2, 4], [2, 2, 5]])

M.det()

Para cada Matriz $A$ invertível, existe uma Matriz inversa $A^{-1}$.

O efeito cumulativo do produto de $A$ e $A^{-1}$ é a matriz identidade: $AA^{-1} = A^{-1}A = \mathbb{1}$

In [30]:
A = Matrix([[1,2],[3,9]])
A

⎡1  2⎤
⎢    ⎥
⎣3  9⎦

A seguir podemos ver a relação de equivalência à $A^{-1}$:

In [31]:
A.inv(), A.inv()*A, A*A.inv()

⎛⎡3   -2/3⎤  ⎡1  0⎤  ⎡1  0⎤⎞
⎜⎢        ⎥, ⎢    ⎥, ⎢    ⎥⎟
⎝⎣-1  1/3 ⎦  ⎣0  1⎦  ⎣0  1⎦⎠

Quando uma matriz é multiplicada por um de seus autovetores o output é o mesmo autovetor multiplicado por uma constante
$A\vec{e}\lambda = \lambda\vec{e}_\lambda$. 

A constante $\lambda$ é chamada de autovalor de $A$.

Para encontrar os autovalores de uma matriz, começa-se pela definição $A\vec{e}_\lambda = \lambda\vec{e}_\lambda$, insere-se a identidade $\mathbb{1}$ e reescreve-se como um problema de espaço nulo:

\begin{equation}A\vec{e}\lambda = \lambda\mathbb{1}\vec{e}_\lambda \Longrightarrow (A - \lambda\mathbb{1})\vec{e}\lambda = \vec{0} \end{equation}

Essa equação terá uma solução quando $|A - \lambda\mathbb{1}| = 0$. Os autovalores de $A \in \mathbb{R}^{n \times m}$, denotados $\{ \lambda1, \lambda2, ..., \lambda n \}$ são raízes do polinômio característico $p(\lambda) = | A - \lambda\mathbb{1}|$

É dessa forma que autovetores e autovalores funcionam no SymPy:

In [32]:
A = Matrix([[9, -2],[-2, 6]])

A.eigenvals()
A.eigenvects()

⎡⎛      ⎡⎡1/2⎤⎤⎞  ⎛       ⎡⎡-2⎤⎤⎞⎤
⎢⎜5, 1, ⎢⎢   ⎥⎥⎟, ⎜10, 1, ⎢⎢  ⎥⎥⎟⎥
⎣⎝      ⎣⎣ 1 ⎦⎦⎠  ⎝       ⎣⎣1 ⎦⎦⎠⎦

Certas matrizes podem ser escritas inteiramente em termos de seus autovetores e seus autovalores. 

Considere a Matrix $\Lambda$ que tem os autovalores da Matriz $A$ em sua diagonal, e a Matriz $Q$ construída dos autovetores de A como colunas:

\begin{equation}
\Lambda =
\begin{bmatrix}
\lambda_1 & ... & 0 \\
... & ... & 0 \\
0 & 0 & \lambda_n
\end{bmatrix} , 
Q =
\begin{bmatrix}
| & ~ & | \\
e\vec{\lambda}_1 & ... & e\vec{\lambda}_n \\
| & ~ & | 
\end{bmatrix} 
\end{equation}

então $ A = Q \Lambda Q^{-1} $

Matrizes que podem ser escritas dessa maneira são chamadas de diagonalizável.

Para diagonalizar uma Matriz $A$ é encontrar suas matrizes $Q$ e $\Lambda$:

In [33]:
A = Matrix([[9, -2], [-2, 6]])
Q, L = A.diagonalize()

Matriz de autovetores $Q$, como colunas:

In [34]:
Q 

⎡1  -2⎤
⎢     ⎥
⎣2  1 ⎦

$Q^{-1}$

In [35]:
Q.inv() 

⎡1/5   2/5⎤
⎢         ⎥
⎣-2/5  1/5⎦

$L$

In [36]:
L

⎡5  0 ⎤
⎢     ⎥
⎣0  10⎦

Realizamos a autodecomposição de $A$:

In [37]:
Q * L * Q.inv() 

⎡9   -2⎤
⎢      ⎥
⎣-2  6 ⎦

Nem todas as matrizes são diagonalizáveis. Você pode checar se uma matriz é diagonalizável chamando o método **is_diagonalizable**:

In [39]:
A.is_diagonalizable()

True

In [38]:
B = Matrix([[1,3],[0,1]])
B.is_diagonalizable()

False

Autovalores de $B$:

In [42]:
B.eigenvals()

Autovetores de $B$:

In [40]:
B.eigenvects()

⎡⎛      ⎡⎡1⎤⎤⎞⎤
⎢⎜1, 2, ⎢⎢ ⎥⎥⎟⎥
⎣⎝      ⎣⎣0⎦⎦⎠⎦

A matriz $B$ não é diagonalizável, porque ela não tem um conjunto completo de autovetores. Para diagonalizar uma matriz $2 \times 2$ nós precisamos de dois autovetores ortogonais, porém B tem somente um único autovetor.